" @keywords link sap.m usually object identifier fir table toolbar title column text columnlistitem
" @summary Usually you use an Object Identifier in the first column of a table. But if you need an active identifier you should use an 'emphasized' link instead.
" @origin sap.m.sample.LinkEmphasized - https://sdk.openui5.org/entity/sap.m.Link/sample/sap.m.sample.LinkEmphasized (status: checked)
CLASS z2ui5_cl_smpc_app_033 DEFINITION PUBLIC.

  PUBLIC SECTION.
    INTERFACES z2ui5_if_app.

    TYPES:
      BEGIN OF ty_s_product,
        product_id      TYPE string,
        name            TYPE string,
        supplier_name   TYPE string,
        width           TYPE string,
        depth           TYPE string,
        height          TYPE string,
        dim_unit        TYPE string,
        weight_measure  TYPE string,
        weight_unit     TYPE string,
        price           TYPE p LENGTH 14 DECIMALS 2,
        currency_code   TYPE string,
        product_pic_url TYPE string,
      END OF ty_s_product.
    DATA t_products TYPE STANDARD TABLE OF ty_s_product WITH EMPTY KEY.

  PROTECTED SECTION.
    DATA client TYPE REF TO z2ui5_if_client.

    METHODS view_display.
    METHODS model_init.

  PRIVATE SECTION.
ENDCLASS.


CLASS z2ui5_cl_smpc_app_033 IMPLEMENTATION.

  METHOD z2ui5_if_app~main.

    me->client = client.
    IF client->check_on_init( ).
      model_init( ).
      view_display( ).
    ELSEIF client->check_on_navigated( ).
      view_display( ).
    ENDIF.

  ENDMETHOD.


  METHOD view_display.

    DATA(view) = z2ui5_cl_ui5_view_builder=>factory( ).

    view->ele( n = `View` ns = `mvc`
        )->a( n = `xmlns`     v = `sap.m`
        )->a( n = `xmlns:mvc` v = `sap.ui.core.mvc`

        )->ele( `Table`
            )->a( n = `id`    v = `idProductsTable`
            )->a( n = `inset` v = `false`
            )->a( n = `items` v = |\{ path: '{ client->_bind_path( t_products ) }', sorter: \{ path: 'NAME' \} \}|

            )->ele( `headerToolbar`
                )->ele( `Toolbar`
                    )->tag( `Title`
                        )->a( n = `text`  v = `Products`
                        )->a( n = `level` v = `H2`

                )->end(
            )->end(

            )->ele( `columns`
                )->ele( `Column`
                    )->a( n = `width` v = `12em`

                    )->tag( `Text`
                        )->a( n = `text` v = `Product`

                )->end(
                )->ele( `Column`
                    )->a( n = `minScreenWidth` v = `Tablet`
                    )->a( n = `demandPopin`    v = `true`

                    )->tag( `Text`
                        )->a( n = `text` v = `Supplier`

                )->end(
                )->ele( `Column`
                    )->a( n = `minScreenWidth` v = `Tablet`
                    )->a( n = `demandPopin`    v = `true`
                    )->a( n = `hAlign`         v = `End`

                    )->tag( `Text`
                        )->a( n = `text` v = `Dimensions`

                )->end(
                )->ele( `Column`
                    )->a( n = `minScreenWidth` v = `Tablet`
                    )->a( n = `demandPopin`    v = `true`
                    )->a( n = `hAlign`         v = `End`

                    )->tag( `Text`
                        )->a( n = `text` v = `Weight`

                )->end(
                )->ele( `Column`
                    )->a( n = `hAlign` v = `End`

                    )->tag( `Text`
                        )->a( n = `text` v = `Price`

                )->end(
            )->end(

            )->ele( `items`
                )->ele( `ColumnListItem`
                    )->ele( `cells`
                        )->tag( `Link`
                            )->a( n = `text`       v = `{PRODUCT_ID}`
                            )->a( n = `emphasized` v = `true`
                            )->a( n = `href`       v = `{PRODUCT_PIC_URL}`
                        )->tag( `Text`
                            )->a( n = `text` v = `{SUPPLIER_NAME}`
                        )->tag( `Text`
                            )->a( n = `text` v = `{WIDTH} x {DEPTH} x {HEIGHT} {DIM_UNIT}`
                        )->tag( `ObjectNumber`
                            )->a( n = `number` v = `{WEIGHT_MEASURE}`
                            )->a( n = `unit`   v = `{WEIGHT_UNIT}`
                        )->tag( `ObjectNumber`
                            )->a( n = `number` v = |\{ parts:[\{path:'PRICE'\},\{path:'CURRENCY_CODE'\}], type:'sap.ui.model.type.Currency', formatOptions:\{showMeasure:false\} \}|
                            )->a( n = `unit`   v = `{CURRENCY_CODE}` ).

    client->view_display( view->stringify( ) ).

  ENDMETHOD.


  METHOD model_init.

    " full mock /ProductCollection (sap/ui/demo/mock/products.json) of the original sample
    t_products = VALUE #(
        ( product_id      = `HT-1000`
          name            = `Notebook Basic 15`
          supplier_name   = `Very Best Screens`
          width           = `30`
          depth           = `18`
          height          = `3`
          dim_unit        = `cm`
          weight_measure  = `4.2`
          weight_unit     = `KG`
          price           = `956.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1000.jpg` )
        ( product_id      = `HT-1001`
          name            = `Notebook Basic 17`
          supplier_name   = `Very Best Screens`
          width           = `29`
          depth           = `17`
          height          = `3.1`
          dim_unit        = `cm`
          weight_measure  = `4.5`
          weight_unit     = `KG`
          price           = `1249.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1001.jpg` )
        ( product_id      = `HT-1002`
          name            = `Notebook Basic 18`
          supplier_name   = `Very Best Screens`
          width           = `28`
          depth           = `19`
          height          = `2.5`
          dim_unit        = `cm`
          weight_measure  = `4.2`
          weight_unit     = `KG`
          price           = `1570.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1002.jpg` )
        ( product_id      = `HT-1003`
          name            = `Notebook Basic 19`
          supplier_name   = `Smartcards`
          width           = `32`
          depth           = `21`
          height          = `4`
          dim_unit        = `cm`
          weight_measure  = `4.2`
          weight_unit     = `KG`
          price           = `1650.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1003.jpg` )
        ( product_id      = `HT-1007`
          name            = `ITelO Vault`
          supplier_name   = `Technocom`
          width           = `32`
          depth           = `22`
          height          = `3`
          dim_unit        = `cm`
          weight_measure  = `0.2`
          weight_unit     = `KG`
          price           = `299.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1007.jpg` )
        ( product_id      = `HT-1010`
          name            = `Notebook Professional 15`
          supplier_name   = `Very Best Screens`
          width           = `33`
          depth           = `20`
          height          = `3`
          dim_unit        = `cm`
          weight_measure  = `4.3`
          weight_unit     = `KG`
          price           = `1999.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1010.jpg` )
        ( product_id      = `HT-1011`
          name            = `Notebook Professional 17`
          supplier_name   = `Very Best Screens`
          width           = `33`
          depth           = `23`
          height          = `2`
          dim_unit        = `cm`
          weight_measure  = `4.1`
          weight_unit     = `KG`
          price           = `2299.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1011.jpg` )
        ( product_id      = `HT-1020`
          name            = `ITelO Vault Net`
          supplier_name   = `Technocom`
          width           = `10`
          depth           = `1.8`
          height          = `17`
          dim_unit        = `cm`
          weight_measure  = `0.16`
          weight_unit     = `KG`
          price           = `459.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1020.jpg` )
        ( product_id      = `HT-1021`
          name            = `ITelO Vault SAT`
          supplier_name   = `Technocom`
          width           = `11`
          depth           = `1.7`
          height          = `18`
          dim_unit        = `cm`
          weight_measure  = `0.18`
          weight_unit     = `KG`
          price           = `149.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1021.jpg` )
        ( product_id      = `HT-1022`
          name            = `Comfort Easy`
          supplier_name   = `Technocom`
          width           = `84`
          depth           = `1.5`
          height          = `14`
          dim_unit        = `cm`
          weight_measure  = `0.2`
          weight_unit     = `KG`
          price           = `1679.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1022.jpg` )
        ( product_id      = `HT-1023`
          name            = `Comfort Senior`
          supplier_name   = `Technocom`
          width           = `80`
          depth           = `1.6`
          height          = `13`
          dim_unit        = `cm`
          weight_measure  = `0.8`
          weight_unit     = `KG`
          price           = `512.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1023.jpg` )
        ( product_id      = `HT-1030`
          name            = `Ergo Screen E-I`
          supplier_name   = `Very Best Screens`
          width           = `37`
          depth           = `12`
          height          = `36`
          dim_unit        = `cm`
          weight_measure  = `21`
          weight_unit     = `KG`
          price           = `230.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1030.jpg` )
        ( product_id      = `HT-1031`
          name            = `Ergo Screen E-II`
          supplier_name   = `Very Best Screens`
          width           = `40.8`
          depth           = `19`
          height          = `43`
          dim_unit        = `cm`
          weight_measure  = `21`
          weight_unit     = `KG`
          price           = `285.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1031.jpg` )
        ( product_id      = `HT-1032`
          name            = `Ergo Screen E-III`
          supplier_name   = `Very Best Screens`
          width           = `40.8`
          depth           = `19`
          height          = `43`
          dim_unit        = `cm`
          weight_measure  = `21`
          weight_unit     = `KG`
          price           = `345.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1032.jpg` )
        ( product_id      = `HT-1035`
          name            = `Flat Basic`
          supplier_name   = `Very Best Screens`
          width           = `39`
          depth           = `20`
          height          = `41`
          dim_unit        = `cm`
          weight_measure  = `14`
          weight_unit     = `KG`
          price           = `399.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1035.jpg` )
        ( product_id      = `HT-1036`
          name            = `Flat Future`
          supplier_name   = `Very Best Screens`
          width           = `45`
          depth           = `26`
          height          = `46`
          dim_unit        = `cm`
          weight_measure  = `15`
          weight_unit     = `KG`
          price           = `430.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1036.jpg` )
        ( product_id      = `HT-1037`
          name            = `Flat XL`
          supplier_name   = `Very Best Screens`
          width           = `54.5`
          depth           = `22.1`
          height          = `39.1`
          dim_unit        = `cm`
          weight_measure  = `17`
          weight_unit     = `KG`
          price           = `1230.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1037.jpg` )
        ( product_id      = `HT-1040`
          name            = `Laser Professional Eco`
          supplier_name   = `Alpha Printers`
          width           = `51`
          depth           = `46`
          height          = `30`
          dim_unit        = `cm`
          weight_measure  = `32`
          weight_unit     = `KG`
          price           = `830.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1040.jpg` )
        ( product_id      = `HT-1041`
          name            = `Laser Basic`
          supplier_name   = `Alpha Printers`
          width           = `48`
          depth           = `42`
          height          = `26`
          dim_unit        = `cm`
          weight_measure  = `23`
          weight_unit     = `KG`
          price           = `490.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1041.jpg` )
        ( product_id      = `HT-1042`
          name            = `Laser Allround`
          supplier_name   = `Alpha Printers`
          width           = `53`
          depth           = `50`
          height          = `65`
          dim_unit        = `cm`
          weight_measure  = `17`
          weight_unit     = `KG`
          price           = `349.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1042.jpg` )
        ( product_id      = `HT-1050`
          name            = `Ultra Jet Super Color`
          supplier_name   = `Alpha Printers`
          width           = `41`
          depth           = `41`
          height          = `28`
          dim_unit        = `cm`
          weight_measure  = `3`
          weight_unit     = `KG`
          price           = `139.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1050.jpg` )
        ( product_id      = `HT-1051`
          name            = `Ultra Jet Mobile`
          supplier_name   = `Printer for All`
          width           = `46`
          depth           = `32`
          height          = `25`
          dim_unit        = `cm`
          weight_measure  = `1.9`
          weight_unit     = `KG`
          price           = `99.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1051.jpg` )
        ( product_id      = `HT-1052`
          name            = `Ultra Jet Super Highspeed`
          supplier_name   = `Printer for All`
          width           = `41`
          depth           = `41`
          height          = `28`
          dim_unit        = `cm`
          weight_measure  = `18`
          weight_unit     = `KG`
          price           = `170.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1052.jpg` )
        ( product_id      = `HT-1055`
          name            = `Multi Print`
          supplier_name   = `Printer for All`
          width           = `55`
          depth           = `45`
          height          = `29`
          dim_unit        = `cm`
          weight_measure  = `6.3`
          weight_unit     = `KG`
          price           = `99.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1055.jpg` )
        ( product_id      = `HT-1056`
          name            = `Multi Color`
          supplier_name   = `Printer for All`
          width           = `51`
          depth           = `41.3`
          height          = `22`
          dim_unit        = `cm`
          weight_measure  = `4.3`
          weight_unit     = `KG`
          price           = `119.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1056.jpg` )
        ( product_id      = `HT-1060`
          name            = `Cordless Mouse`
          supplier_name   = `Oxynum`
          width           = `6`
          depth           = `14.5`
          height          = `3.5`
          dim_unit        = `cm`
          weight_measure  = `0.09`
          weight_unit     = `KG`
          price           = `9.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1060.jpg` )
        ( product_id      = `HT-1061`
          name            = `Speed Mouse`
          supplier_name   = `Oxynum`
          width           = `7`
          depth           = `15`
          height          = `3.1`
          dim_unit        = `cm`
          weight_measure  = `0.09`
          weight_unit     = `KG`
          price           = `7.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1061.jpg` )
        ( product_id      = `HT-1062`
          name            = `Track Mouse`
          supplier_name   = `Oxynum`
          width           = `3`
          depth           = `7`
          height          = `4`
          dim_unit        = `cm`
          weight_measure  = `0.03`
          weight_unit     = `KG`
          price           = `11.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1062.jpg` )
        ( product_id      = `HT-1063`
          name            = `Ergonomic Keyboard`
          supplier_name   = `Oxynum`
          width           = `50`
          depth           = `21`
          height          = `3.5`
          dim_unit        = `cm`
          weight_measure  = `2.1`
          weight_unit     = `KG`
          price           = `14.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1063.jpg` )
        ( product_id      = `HT-1064`
          name            = `Internet Keyboard`
          supplier_name   = `Oxynum`
          width           = `52`
          depth           = `25`
          height          = `3`
          dim_unit        = `cm`
          weight_measure  = `1.8`
          weight_unit     = `KG`
          price           = `16.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1064.jpg` )
        ( product_id      = `HT-1065`
          name            = `Media Keyboard`
          supplier_name   = `Oxynum`
          width           = `51.4`
          depth           = `23`
          height          = `4`
          dim_unit        = `cm`
          weight_measure  = `2.3`
          weight_unit     = `KG`
          price           = `26.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1065.jpg` )
        ( product_id      = `HT-1066`
          name            = `Mousepad`
          supplier_name   = `Oxynum`
          width           = `15`
          depth           = `6`
          height          = `0.2`
          dim_unit        = `cm`
          weight_measure  = `80`
          weight_unit     = `G`
          price           = `6.99`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1066.jpg` )
        ( product_id      = `HT-1067`
          name            = `Ergo Mousepad`
          supplier_name   = `Oxynum`
          width           = `15`
          depth           = `6`
          height          = `0.2`
          dim_unit        = `cm`
          weight_measure  = `80`
          weight_unit     = `G`
          price           = `8.99`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1067.jpg` )
        ( product_id      = `HT-1068`
          name            = `Designer Mousepad`
          supplier_name   = `Fasttech`
          width           = `24`
          depth           = `24`
          height          = `0.6`
          dim_unit        = `cm`
          weight_measure  = `90`
          weight_unit     = `G`
          price           = `12.99`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1068.jpg` )
        ( product_id      = `HT-1069`
          name            = `Universal card reader`
          supplier_name   = `Fasttech`
          width           = `6`
          depth           = `6`
          height          = `3`
          dim_unit        = `cm`
          weight_measure  = `45`
          weight_unit     = `G`
          price           = `14.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1069.jpg` )
        ( product_id      = `HT-1070`
          name            = `Proctra X`
          supplier_name   = `Ultrasonic United`
          width           = `22`
          depth           = `35`
          height          = `17`
          dim_unit        = `cm`
          weight_measure  = `0.255`
          weight_unit     = `KG`
          price           = `70.90`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1070.jpg` )
        ( product_id      = `HT-1071`
          name            = `Gladiator MX`
          supplier_name   = `Ultrasonic United`
          width           = `22`
          depth           = `35`
          height          = `17`
          dim_unit        = `cm`
          weight_measure  = `0.3`
          weight_unit     = `KG`
          price           = `81.70`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1071.jpg` )
        ( product_id      = `HT-1072`
          name            = `Hurricane GX`
          supplier_name   = `Ultrasonic United`
          width           = `22`
          depth           = `35`
          height          = `17`
          dim_unit        = `cm`
          weight_measure  = `0.4`
          weight_unit     = `KG`
          price           = `101.20`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1072.jpg` )
        ( product_id      = `HT-1073`
          name            = `Hurricane GX/LN`
          supplier_name   = `Smartcards`
          width           = `22`
          depth           = `35`
          height          = `17`
          dim_unit        = `cm`
          weight_measure  = `0.4`
          weight_unit     = `KG`
          price           = `139.99`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1073.jpg` )
        ( product_id      = `HT-1080`
          name            = `Photo Scan`
          supplier_name   = `Printer for All`
          width           = `34`
          depth           = `48`
          height          = `5`
          dim_unit        = `cm`
          weight_measure  = `2.3`
          weight_unit     = `KG`
          price           = `129.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1080.jpg` )
        ( product_id      = `HT-1081`
          name            = `Power Scan`
          supplier_name   = `Printer for All`
          width           = `31`
          depth           = `43`
          height          = `7`
          dim_unit        = `cm`
          weight_measure  = `2.4`
          weight_unit     = `KG`
          price           = `89.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1081.jpg` )
        ( product_id      = `HT-1082`
          name            = `Jet Scan Professional`
          supplier_name   = `Printer for All`
          width           = `33`
          depth           = `41`
          height          = `12`
          dim_unit        = `cm`
          weight_measure  = `3.2`
          weight_unit     = `KG`
          price           = `169.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1082.jpg` )
        ( product_id      = `HT-1083`
          name            = `Jet Scan Professional`
          supplier_name   = `Printer for All`
          width           = `35`
          depth           = `40`
          height          = `10`
          dim_unit        = `cm`
          weight_measure  = `3.2`
          weight_unit     = `KG`
          price           = `189.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1083.jpg` )
        ( product_id      = `HT-1085`
          name            = `Copymaster`
          supplier_name   = `Alpha Printers`
          width           = `45`
          depth           = `42`
          height          = `22`
          dim_unit        = `cm`
          weight_measure  = `23.2`
          weight_unit     = `KG`
          price           = `1499.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1085.jpg` )
        ( product_id      = `HT-1090`
          name            = `Surround Sound`
          supplier_name   = `Speaker Experts`
          width           = `12`
          depth           = `10`
          height          = `16`
          dim_unit        = `cm`
          weight_measure  = `3`
          weight_unit     = `KG`
          price           = `39.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1090.jpg` )
        ( product_id      = `HT-1091`
          name            = `Blaster Extreme`
          supplier_name   = `Speaker Experts`
          width           = `13`
          depth           = `11`
          height          = `17.5`
          dim_unit        = `cm`
          weight_measure  = `1.4`
          weight_unit     = `KG`
          price           = `26.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1091.jpg` )
        ( product_id      = `HT-1092`
          name            = `Sound Booster`
          supplier_name   = `Speaker Experts`
          width           = `12.4`
          depth           = `10.4`
          height          = `18.1`
          dim_unit        = `cm`
          weight_measure  = `2.1`
          weight_unit     = `KG`
          price           = `45.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1092.jpg` )
        ( product_id      = `HT-1095`
          name            = `Lovely Sound 5.1 Wireless`
          supplier_name   = `Fasttech`
          width           = `24`
          depth           = `19`
          height          = `23`
          dim_unit        = `cm`
          weight_measure  = `80`
          weight_unit     = `G`
          price           = `49.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1095.jpg` )
        ( product_id      = `HT-1096`
          name            = `Lovely Sound 5.1`
          supplier_name   = `Fasttech`
          width           = `25`
          depth           = `17`
          height          = `19`
          dim_unit        = `cm`
          weight_measure  = `130`
          weight_unit     = `G`
          price           = `39.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1096.jpg` )
        ( product_id      = `HT-1097`
          name            = `Lovely Sound Stereo`
          supplier_name   = `Fasttech`
          width           = `21.3`
          depth           = `2.4`
          height          = `19.7`
          dim_unit        = `cm`
          weight_measure  = `60`
          weight_unit     = `G`
          price           = `29.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1097.jpg` )
        ( product_id      = `HT-1100`
          name            = `Smart Office`
          supplier_name   = `Technocom`
          width           = `15`
          depth           = `6.5`
          height          = `2.1`
          dim_unit        = `cm`
          weight_measure  = `1.2`
          weight_unit     = `KG`
          price           = `89.90`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1100.jpg` )
        ( product_id      = `HT-1101`
          name            = `Smart Design`
          supplier_name   = `Technocom`
          width           = `14`
          depth           = `6.7`
          height          = `24`
          dim_unit        = `cm`
          weight_measure  = `0.8`
          weight_unit     = `KG`
          price           = `79.90`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1101.jpg` )
        ( product_id      = `HT-1102`
          name            = `Smart Network`
          supplier_name   = `Technocom`
          width           = `16`
          depth           = `6`
          height          = `27`
          dim_unit        = `cm`
          weight_measure  = `0.8`
          weight_unit     = `KG`
          price           = `69.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1102.jpg` )
        ( product_id      = `HT-1103`
          name            = `Smart Multimedia`
          supplier_name   = `Technocom`
          width           = `11`
          depth           = `3.4`
          height          = `22`
          dim_unit        = `cm`
          weight_measure  = `0.8`
          weight_unit     = `KG`
          price           = `77.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1103.jpg` )
        ( product_id      = `HT-1104`
          name            = `Smart Games`
          supplier_name   = `Technocom`
          width           = `10`
          depth           = `3`
          height          = `30`
          dim_unit        = `cm`
          weight_measure  = `1.1`
          weight_unit     = `KG`
          price           = `55.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1104.jpg` )
        ( product_id      = `HT-1105`
          name            = `Smart Internet Antivirus`
          supplier_name   = `Brainsoft`
          width           = `16`
          depth           = `4`
          height          = `21`
          dim_unit        = `cm`
          weight_measure  = `0.7`
          weight_unit     = `KG`
          price           = `29.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1105.jpg` )
        ( product_id      = `HT-1106`
          name            = `Smart Firewall`
          supplier_name   = `Brainsoft`
          width           = `17.9`
          depth           = `4.2`
          height          = `23.1`
          dim_unit        = `cm`
          weight_measure  = `0.9`
          weight_unit     = `KG`
          price           = `34.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1106.jpg` )
        ( product_id      = `HT-1107`
          name            = `Smart Money`
          supplier_name   = `Brainsoft`
          width           = `12`
          depth           = `1.5`
          height          = `19`
          dim_unit        = `cm`
          weight_measure  = `0.5`
          weight_unit     = `KG`
          price           = `29.90`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1107.jpg` )
        ( product_id      = `HT-1110`
          name            = `PC Lock`
          supplier_name   = `Red Point Stores`
          width           = `20`
          depth           = `8`
          height          = `4.3`
          dim_unit        = `cm`
          weight_measure  = `0.03`
          weight_unit     = `KG`
          price           = `8.90`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1110.jpg` )
        ( product_id      = `HT-1111`
          name            = `Notebook Lock`
          supplier_name   = `Red Point Stores`
          width           = `31`
          depth           = `9`
          height          = `7`
          dim_unit        = `cm`
          weight_measure  = `0.02`
          weight_unit     = `KG`
          price           = `6.90`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1111.jpg` )
        ( product_id      = `HT-1112`
          name            = `Web cam reality`
          supplier_name   = `Red Point Stores`
          width           = `9`
          depth           = `8.2`
          height          = `1.3`
          dim_unit        = `cm`
          weight_measure  = `0.075`
          weight_unit     = `KG`
          price           = `39.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1112.jpg` )
        ( product_id      = `HT-1113`
          name            = `Screen clean`
          supplier_name   = `Red Point Stores`
          width           = `2`
          depth           = `2`
          height          = `0.1`
          dim_unit        = `cm`
          weight_measure  = `0.05`
          weight_unit     = `KG`
          price           = `2.30`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1113.jpg` )
        ( product_id      = `HT-1114`
          name            = `Fabric bag professional`
          supplier_name   = `Red Point Stores`
          width           = `42`
          depth           = `32`
          height          = `7`
          dim_unit        = `cm`
          weight_measure  = `1.8`
          weight_unit     = `KG`
          price           = `31.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1114.jpg` )
        ( product_id      = `HT-1115`
          name            = `Wireless DSL Router`
          supplier_name   = `Red Point Stores`
          width           = `19.3`
          depth           = `18`
          height          = `5`
          dim_unit        = `cm`
          weight_measure  = `0.45`
          weight_unit     = `KG`
          price           = `49.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1115.jpg` )
        ( product_id      = `HT-1116`
          name            = `Wireless DSL Router / Repeater`
          supplier_name   = `Red Point Stores`
          width           = `19.3`
          depth           = `18`
          height          = `5`
          dim_unit        = `cm`
          weight_measure  = `0.45`
          weight_unit     = `KG`
          price           = `59.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1116.jpg` )
        ( product_id      = `HT-1117`
          name            = `Wireless DSL Router / Repeater and Print Server`
          supplier_name   = `Technocom`
          width           = `19.3`
          depth           = `18`
          height          = `5`
          dim_unit        = `cm`
          weight_measure  = `0.45`
          weight_unit     = `KG`
          price           = `69.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1117.jpg` )
        ( product_id      = `HT-1118`
          name            = `USB Stick`
          supplier_name   = `Technocom`
          width           = `1.5`
          depth           = `8.7`
          height          = `1.2`
          dim_unit        = `cm`
          weight_measure  = `0.015`
          weight_unit     = `KG`
          price           = `35.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1118.jpg` )
        ( product_id      = `HT-1119`
          name            = `Travel Adapter`
          supplier_name   = `Titanium`
          width           = `2`
          depth           = `3.1`
          height          = `3.9`
          dim_unit        = `cm`
          weight_measure  = `88`
          weight_unit     = `G`
          price           = `79.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1119.jpg` )
        ( product_id      = `HT-1120`
          name            = `Cordless Bluetooth Keyboard, english international`
          supplier_name   = `Technocom`
          width           = `51.4`
          depth           = `23`
          height          = `4`
          dim_unit        = `cm`
          weight_measure  = `1`
          weight_unit     = `KG`
          price           = `29.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1120.jpg` )
        ( product_id      = `HT-1137`
          name            = `Flat XXL`
          supplier_name   = `Technocom`
          width           = `54`
          depth           = `22`
          height          = `38`
          dim_unit        = `cm`
          weight_measure  = `18`
          weight_unit     = `KG`
          price           = `1430.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1137.jpg` )
        ( product_id      = `HT-1138`
          name            = `Pocket Mouse`
          supplier_name   = `Technocom`
          width           = `0.3`
          depth           = `0.5`
          height          = `1`
          dim_unit        = `cm`
          weight_measure  = `0.02`
          weight_unit     = `KG`
          price           = `23.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1138.jpg` )
        ( product_id      = `HT-1210`
          name            = `PC Power Station`
          supplier_name   = `Technocom`
          width           = `28`
          depth           = `31`
          height          = `43`
          dim_unit        = `cm`
          weight_measure  = `2.3`
          weight_unit     = `KG`
          price           = `2399.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1210.jpg` )
        ( product_id      = `HT-1251`
          name            = `Astro Laptop 1516`
          supplier_name   = `Ultrasonic United`
          width           = `30`
          depth           = `18`
          height          = `3`
          dim_unit        = `cm`
          weight_measure  = `4.2`
          weight_unit     = `KG`
          price           = `989.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1251.jpg` )
        ( product_id      = `HT-1252`
          name            = `Astro Phone 6`
          supplier_name   = `Ultrasonic United`
          width           = `8`
          depth           = `6`
          height          = `1.5`
          dim_unit        = `cm`
          weight_measure  = `0.75`
          weight_unit     = `KG`
          price           = `649.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1252.jpg` )
        ( product_id      = `HT-1253`
          name            = `Benda Laptop 1408`
          supplier_name   = `Ultrasonic United`
          width           = `30`
          depth           = `18`
          height          = `3`
          dim_unit        = `cm`
          weight_measure  = `4.2`
          weight_unit     = `KG`
          price           = `976.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1253.jpg` )
        ( product_id      = `HT-1254`
          name            = `Bending Screen 21HD`
          supplier_name   = `Ultrasonic United`
          width           = `37`
          depth           = `12`
          height          = `36`
          dim_unit        = `cm`
          weight_measure  = `15`
          weight_unit     = `KG`
          price           = `250.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1254.jpg` )
        ( product_id      = `HT-1255`
          name            = `Broad Screen 22HD`
          supplier_name   = `Ultrasonic United`
          width           = `39`
          depth           = `12`
          height          = `38`
          dim_unit        = `cm`
          weight_measure  = `16`
          weight_unit     = `KG`
          price           = `270.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1255.jpg` )
        ( product_id      = `HT-1256`
          name            = `Cerdik Phone 7`
          supplier_name   = `Ultrasonic United`
          width           = `9`
          depth           = `15`
          height          = `1.5`
          dim_unit        = `cm`
          weight_measure  = `0.75`
          weight_unit     = `KG`
          price           = `549.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1256.jpg` )
        ( product_id      = `HT-1257`
          name            = `Cepat Tablet 10.5`
          supplier_name   = `Ultrasonic United`
          width           = `48`
          depth           = `31`
          height          = `4.5`
          dim_unit        = `cm`
          weight_measure  = `2.8`
          weight_unit     = `KG`
          price           = `549.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1257.jpg` )
        ( product_id      = `HT-1258`
          name            = `Cepat Tablet 8`
          supplier_name   = `Ultrasonic United`
          width           = `38`
          depth           = `21`
          height          = `3.5`
          dim_unit        = `cm`
          weight_measure  = `2.5`
          weight_unit     = `KG`
          price           = `529.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1258.jpg` )
        ( product_id      = `HT-1500`
          name            = `Server Basic`
          supplier_name   = `Technocom`
          width           = `34`
          depth           = `35`
          height          = `23`
          dim_unit        = `cm`
          weight_measure  = `18`
          weight_unit     = `KG`
          price           = `5000.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1500.jpg` )
        ( product_id      = `HT-1501`
          name            = `Server Professional`
          supplier_name   = `Technocom`
          width           = `29`
          depth           = `30`
          height          = `27`
          dim_unit        = `cm`
          weight_measure  = `25`
          weight_unit     = `KG`
          price           = `15000.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1501.jpg` )
        ( product_id      = `HT-1502`
          name            = `Server Power Pro`
          supplier_name   = `Technocom`
          width           = `22`
          depth           = `27.3`
          height          = `37`
          dim_unit        = `cm`
          weight_measure  = `35`
          weight_unit     = `KG`
          price           = `25000.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1502.jpg` )
        ( product_id      = `HT-1600`
          name            = `Family PC Basic`
          supplier_name   = `Titanium`
          width           = `21.4`
          depth           = `29`
          height          = `38`
          dim_unit        = `cm`
          weight_measure  = `4.8`
          weight_unit     = `KG`
          price           = `600.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1600.jpg` )
        ( product_id      = `HT-1601`
          name            = `Family PC Pro`
          supplier_name   = `Titanium`
          width           = `25`
          depth           = `31.7`
          height          = `40.2`
          dim_unit        = `cm`
          weight_measure  = `5.3`
          weight_unit     = `KG`
          price           = `900.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1601.jpg` )
        ( product_id      = `HT-1602`
          name            = `Gaming Monster`
          supplier_name   = `Titanium`
          width           = `26.5`
          depth           = `34`
          height          = `47`
          dim_unit        = `cm`
          weight_measure  = `5.9`
          weight_unit     = `KG`
          price           = `1200.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1602.jpg` )
        ( product_id      = `HT-1603`
          name            = `Gaming Monster Pro`
          supplier_name   = `Titanium`
          width           = `27`
          depth           = `28`
          height          = `42`
          dim_unit        = `cm`
          weight_measure  = `6.8`
          weight_unit     = `KG`
          price           = `1700.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-1603.jpg` )
        ( product_id      = `HT-2000`
          name            = `7" Widescreen Portable DVD Player w MP3`
          supplier_name   = `Titanium`
          width           = `21.4`
          depth           = `19`
          height          = `27.6`
          dim_unit        = `cm`
          weight_measure  = `0.79`
          weight_unit     = `KG`
          price           = `249.99`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-2000.jpg` )
        ( product_id      = `HT-2001`
          name            = `10" Portable DVD player`
          supplier_name   = `Titanium`
          width           = `24`
          depth           = `19.5`
          height          = `29`
          dim_unit        = `cm`
          weight_measure  = `0.84`
          weight_unit     = `KG`
          price           = `449.99`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-2001.jpg` )
        ( product_id      = `HT-2002`
          name            = `Portable DVD Player with 9" LCD Monitor`
          supplier_name   = `Technocom`
          width           = `21`
          depth           = `16.5`
          height          = `14`
          dim_unit        = `cm`
          weight_measure  = `0.72`
          weight_unit     = `KG`
          price           = `853.99`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-2002.jpg` )
        ( product_id      = `HT-2025`
          name            = `CD/DVD case: 264 sleeves`
          supplier_name   = `Titanium`
          width           = `13`
          depth           = `13`
          height          = `20`
          dim_unit        = `cm`
          weight_measure  = `0.65`
          weight_unit     = `KG`
          price           = `44.99`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-2025.jpg` )
        ( product_id      = `HT-2026`
          name            = `Audio/Video Cable Kit - 4m`
          supplier_name   = `Titanium`
          width           = `21`
          depth           = `10.2`
          height          = `13`
          dim_unit        = `cm`
          weight_measure  = `0.2`
          weight_unit     = `KG`
          price           = `29.99`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-2026.jpg` )
        ( product_id      = `HT-2027`
          name            = `Removable CD/DVD Laser Labels`
          supplier_name   = `Titanium`
          width           = `5.5`
          depth           = `2`
          height          = `2`
          dim_unit        = `cm`
          weight_measure  = `0.15`
          weight_unit     = `KG`
          price           = `8.99`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-2027.jpg` )
        ( product_id      = `HT-6100`
          name            = `Beam Breaker B-1`
          supplier_name   = `Titanium`
          width           = `30.4`
          depth           = `23.1`
          height          = `23`
          dim_unit        = `cm`
          weight_measure  = `1.7`
          weight_unit     = `KG`
          price           = `469.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-6100.jpg` )
        ( product_id      = `HT-6101`
          name            = `Beam Breaker B-2`
          supplier_name   = `Technocom`
          width           = `30.4`
          depth           = `23.1`
          height          = `23`
          dim_unit        = `cm`
          weight_measure  = `2`
          weight_unit     = `KG`
          price           = `679.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-6101.jpg` )
        ( product_id      = `HT-6102`
          name            = `Beam Breaker B-3`
          supplier_name   = `Technocom`
          width           = `30.4`
          depth           = `23.1`
          height          = `23`
          dim_unit        = `cm`
          weight_measure  = `2.5`
          weight_unit     = `KG`
          price           = `889.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-6102.jpg` )
        ( product_id      = `HT-6110`
          name            = `Play Movie`
          supplier_name   = `Fasttech`
          width           = `37`
          depth           = `24`
          height          = `6`
          dim_unit        = `cm`
          weight_measure  = `2.4`
          weight_unit     = `KG`
          price           = `130.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-6110.jpg` )
        ( product_id      = `HT-6111`
          name            = `Record Movie`
          supplier_name   = `Fasttech`
          width           = `38`
          depth           = `26`
          height          = `6.2`
          dim_unit        = `cm`
          weight_measure  = `3.1`
          weight_unit     = `KG`
          price           = `288.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-6111.jpg` )
        ( product_id      = `HT-6120`
          name            = `ITelo MusicStick`
          supplier_name   = `Fasttech`
          width           = `1.5`
          depth           = `6`
          height          = `1`
          dim_unit        = `cm`
          weight_measure  = `134`
          weight_unit     = `G`
          price           = `45.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-6120.jpg` )
        ( product_id      = `HT-6121`
          name            = `ITelo Jog-Mate`
          supplier_name   = `Fasttech`
          width           = `5.1`
          depth           = `8`
          height          = `9.2`
          dim_unit        = `cm`
          weight_measure  = `134`
          weight_unit     = `G`
          price           = `63.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-6121.jpg` )
        ( product_id      = `HT-6122`
          name            = `Power Pro Player 40`
          supplier_name   = `Fasttech`
          width           = `5.1`
          depth           = `8`
          height          = `9.2`
          dim_unit        = `cm`
          weight_measure  = `266`
          weight_unit     = `G`
          price           = `167.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-6122.jpg` )
        ( product_id      = `HT-6123`
          name            = `Power Pro Player 80`
          supplier_name   = `Fasttech`
          width           = `4`
          depth           = `6`
          height          = `0.8`
          dim_unit        = `cm`
          weight_measure  = `267`
          weight_unit     = `G`
          price           = `299.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-6123.jpg` )
        ( product_id      = `HT-6130`
          name            = `Flat Watch HD32`
          supplier_name   = `Very Best Screens`
          width           = `78`
          depth           = `22.1`
          height          = `55`
          dim_unit        = `cm`
          weight_measure  = `2.6`
          weight_unit     = `KG`
          price           = `1459.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-6130.jpg` )
        ( product_id      = `HT-6131`
          name            = `Flat Watch HD37`
          supplier_name   = `Very Best Screens`
          width           = `99.1`
          depth           = `26`
          height          = `61`
          dim_unit        = `cm`
          weight_measure  = `2.2`
          weight_unit     = `KG`
          price           = `1199.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-6131.jpg` )
        ( product_id      = `HT-6132`
          name            = `Flat Watch HD41`
          supplier_name   = `Very Best Screens`
          width           = `128`
          depth           = `23`
          height          = `79.1`
          dim_unit        = `cm`
          weight_measure  = `1.8`
          weight_unit     = `KG`
          price           = `899.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-6132.jpg` )
        ( product_id      = `HT-7000`
          name            = `Copperberry`
          supplier_name   = `Fasttech`
          width           = `8.1`
          depth           = `13`
          height          = `12.1`
          dim_unit        = `cm`
          weight_measure  = `0.5`
          weight_unit     = `KG`
          price           = `549.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-7000.jpg` )
        ( product_id      = `HT-7010`
          name            = `Silverberry`
          supplier_name   = `Fasttech`
          width           = `8.1`
          depth           = `13`
          height          = `12.1`
          dim_unit        = `cm`
          weight_measure  = `0.5`
          weight_unit     = `KG`
          price           = `549.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-7010.jpg` )
        ( product_id      = `HT-7020`
          name            = `Goldberry`
          supplier_name   = `Fasttech`
          width           = `8.1`
          depth           = `13`
          height          = `12.1`
          dim_unit        = `cm`
          weight_measure  = `0.5`
          weight_unit     = `KG`
          price           = `549.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-7020.jpg` )
        ( product_id      = `HT-7030`
          name            = `Platinberry`
          supplier_name   = `Fasttech`
          width           = `8.1`
          depth           = `13`
          height          = `12.1`
          dim_unit        = `cm`
          weight_measure  = `0.5`
          weight_unit     = `KG`
          price           = `549.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-7030.jpg` )
        ( product_id      = `HT-8000`
          name            = `ITelO FlexTop I4000`
          supplier_name   = `Titanium`
          width           = `31`
          depth           = `19`
          height          = `3.1`
          dim_unit        = `cm`
          weight_measure  = `4`
          weight_unit     = `KG`
          price           = `799.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-8000.jpg` )
        ( product_id      = `HT-8001`
          name            = `ITelO FlexTop I6300c`
          supplier_name   = `Titanium`
          width           = `32`
          depth           = `20`
          height          = `3.4`
          dim_unit        = `cm`
          weight_measure  = `4.2`
          weight_unit     = `KG`
          price           = `799.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-8001.jpg` )
        ( product_id      = `HT-8002`
          name            = `ITelO FlexTop I9100`
          supplier_name   = `Titanium`
          width           = `38`
          depth           = `21`
          height          = `4.1`
          dim_unit        = `cm`
          weight_measure  = `3.5`
          weight_unit     = `KG`
          price           = `1199.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-8002.jpg` )
        ( product_id      = `HT-8003`
          name            = `ITelO FlexTop I9800`
          supplier_name   = `Titanium`
          width           = `48`
          depth           = `31`
          height          = `4.5`
          dim_unit        = `cm`
          weight_measure  = `3.8`
          weight_unit     = `KG`
          price           = `1388.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-8003.jpg` )
        ( product_id      = `HT-9991`
          name            = `Smartphone Leather Case`
          supplier_name   = `Ultrasonic United`
          width           = `48`
          depth           = `31`
          height          = `4.5`
          dim_unit        = `cm`
          weight_measure  = `0.02`
          weight_unit     = `KG`
          price           = `25.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-9991.jpg` )
        ( product_id      = `HT-9992`
          name            = `Smartphone Alpha`
          supplier_name   = `Ultrasonic United`
          width           = `48`
          depth           = `31`
          height          = `4.5`
          dim_unit        = `cm`
          weight_measure  = `0.75`
          weight_unit     = `KG`
          price           = `599.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-9992.jpg` )
        ( product_id      = `HT-9993`
          name            = `Mini Tablet`
          supplier_name   = `Ultrasonic United`
          width           = `48`
          depth           = `31`
          height          = `4.5`
          dim_unit        = `cm`
          weight_measure  = `3.8`
          weight_unit     = `KG`
          price           = `833.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-9993.jpg` )
        ( product_id      = `HT-9994`
          name            = `Camcorder View`
          supplier_name   = `Ultrasonic United`
          width           = `48`
          depth           = `31`
          height          = `27`
          dim_unit        = `cm`
          weight_measure  = `3.8`
          weight_unit     = `KG`
          price           = `1388.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-9994.jpg` )
        ( product_id      = `HT-9995`
          name            = `Tablet Pouch`
          supplier_name   = `Titanium`
          width           = `25`
          depth           = `40`
          height          = `4.5`
          dim_unit        = `cm`
          weight_measure  = `0.03`
          weight_unit     = `KG`
          price           = `20.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-9995.jpg` )
        ( product_id      = `HT-9996`
          name            = `Tablet Pouch`
          supplier_name   = `Titanium`
          width           = `25`
          depth           = `40`
          height          = `4.5`
          dim_unit        = `cm`
          weight_measure  = `0.03`
          weight_unit     = `KG`
          price           = `20.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-9996.jpg` )
        ( product_id      = `HT-9997`
          name            = `e-Book Reader ReadMe`
          supplier_name   = `Titanium`
          width           = `48`
          depth           = `31`
          height          = `4.5`
          dim_unit        = `cm`
          weight_measure  = `3.8`
          weight_unit     = `KG`
          price           = `33.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-9997.jpg` )
        ( product_id      = `HT-9998`
          name            = `Smartphone Beta`
          supplier_name   = `Titanium`
          width           = `48`
          depth           = `31`
          height          = `4.5`
          dim_unit        = `cm`
          weight_measure  = `0.75`
          weight_unit     = `KG`
          price           = `30.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-9998.jpg` )
        ( product_id      = `HT-9999`
          name            = `Maxi Tablet`
          supplier_name   = `Titanium`
          width           = `48`
          depth           = `31`
          height          = `4.5`
          dim_unit        = `cm`
          weight_measure  = `3.8`
          weight_unit     = `KG`
          price           = `749.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/HT-9999.jpg` )
        ( product_id      = `PF-1000`
          name            = `Flyer`
          supplier_name   = `Titanium`
          width           = `46`
          depth           = `30`
          height          = `3`
          dim_unit        = `cm`
          weight_measure  = `0.01`
          weight_unit     = `KG`
          price           = `0.00`
          currency_code   = `EUR`
          product_pic_url = `https://sdk.openui5.org/test-resources/sap/ui/documentation/sdk/images/PF-1000.jpg` ) ).

  ENDMETHOD.

ENDCLASS.
